### ISSUE TITLE
Issue with dgpost 2.1 

### ISSUE THREAD

**Issue by NukP** [dgbowl/dgpost#89]
I am now working on implementing the yadg 5 upgrade to the pipeline of CO2 reduction e.chem data analysis. I folked yadg 5.0 and use this version to create the datagram.nc file. While running yadg, I also encountered some errors. So, I had to make some minor adjustments to the script, but I eventually could get datagram.nc file. Now that I use this datagram.nc to run dgpost, I encounterd an error. I am not sure whether this is the issue with dgpost itself or it is something with the .nc file itself. 

Please find attached the ymal and datagram (.nc) file used in the run as follows: https://drive.switch.ch/index.php/s/fb1oqUuXDz9HRXW

__I ran dgpost using the following command:__

`dgpost "C:\Users\plnu\Dropbox\PythonStuff\Empa\Notebooks\Empa_30 Testing yadg5\Test auto DB\AutoDB\Recipe\dgpost\dgpost.recipe.01_electro_v5.yaml" --patch "C:\Users\plnu\Dropbox\PythonStuff\Empa\Notebooks\Empa_30 Testing yadg5\Test auto DB\AutoDB\Output\test_fran_file\datagram_test_fran_file" -v`

__But got the following error:__

`INFO:dgpost.main:Processing 'load'.
Traceback (most recent call last):
  File "C:\Users\plnu\Anaconda3\envs\test_yadg5\lib\site-packages\xarray\backends\file_manager.py", line 211, in _acquire_with_cache_info
    file = self._cache[self._key]
  File "C:\Users\plnu\Anaconda3\envs\test_yadg5\lib\site-packages\xarray\backends\lru_cache.py", line 56, in __getitem__
    value = self._cache[key]
KeyError: [<class 'h5netcdf.core.File'>, ('C:\\Users\\plnu\\Dropbox\\PythonStuff\\Empa\\Notebooks\\Empa_30 Testing yadg5\\Test auto DB\\AutoDB\\Output\\test_fran_file\\datagram_test_fran_file.nc',), 'r', (('decode_vlen_strings', True), ('invalid_netcdf', None)), '4f541ab0-0650-487e-9c15-0232df7eec9c']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\plnu\Anaconda3\envs\test_yadg5\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\plnu\Anaconda3\envs\test_yadg5\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\plnu\Anaconda3\envs\test_yadg5\Scripts\dgpost.exe\__main__.py", line 7, in <module>
  File "C:\Users\plnu\Anaconda3\envs\test_yadg5\lib\site-packages\dgpost\main.py", line 229, in run_with_arguments
    run(args.infile, patch=args.patch)
  File "C:\Users\plnu\Anaconda3\envs\test_yadg5\lib\site-packages\dgpost\main.py", line 95, in run
    tables[el["as"]] = load(fp, None, el["type"])
  File "C:\Users\plnu\Anaconda3\envs\test_yadg5\lib\site-packages\dgpost\utils\load.py", line 51, in load
    return datatree.open_datatree(path, engine="h5netcdf")
  File "C:\Users\plnu\Anaconda3\envs\test_yadg5\lib\site-packages\datatree\io.py", line 58, in open_datatree
    return _open_datatree_netcdf(filename_or_obj, engine=engine, **kwargs)
  File "C:\Users\plnu\Anaconda3\envs\test_yadg5\lib\site-packages\datatree\io.py", line 66, in _open_datatree_netcdf
    ds = open_dataset(filename, **kwargs)
  File "C:\Users\plnu\Anaconda3\envs\test_yadg5\lib\site-packages\xarray\backends\api.py", line 573, in open_dataset
    backend_ds = backend.open_dataset(
  File "C:\Users\plnu\Anaconda3\envs\test_yadg5\lib\site-packages\xarray\backends\h5netcdf_.py", line 402, in open_dataset
    store = H5NetCDFStore.open(
  File "C:\Users\plnu\Anaconda3\envs\test_yadg5\lib\site-packages\xarray\backends\h5netcdf_.py", line 175, in open
    return cls(manager, group=group, mode=mode, lock=lock, autoclose=autoclose)
  File "C:\Users\plnu\Anaconda3\envs\test_yadg5\lib\site-packages\xarray\backends\h5netcdf_.py", line 126, in __init__
    self._filename = find_root_and_group(self.ds)[0].filename
  File "C:\Users\plnu\Anaconda3\envs\test_yadg5\lib\site-packages\xarray\backends\h5netcdf_.py", line 186, in ds
    return self._acquire()
  File "C:\Users\plnu\Anaconda3\envs\test_yadg5\lib\site-packages\xarray\backends\h5netcdf_.py", line 178, in _acquire
    with self._manager.acquire_context(needs_lock) as root:
  File "C:\Users\plnu\Anaconda3\envs\test_yadg5\lib\contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "C:\Users\plnu\Anaconda3\envs\test_yadg5\lib\site-packages\xarray\backends\file_manager.py", line 199, in acquire_context
    file, cached = self._acquire_with_cache_info(needs_lock)
  File "C:\Users\plnu\Anaconda3\envs\test_yadg5\lib\site-packages\xarray\backends\file_manager.py", line 217, in _acquire_with_cache_info
    file = self._opener(*self._args, **kwargs)
  File "C:\Users\plnu\Anaconda3\envs\test_yadg5\lib\site-packages\h5netcdf\core.py", line 1051, in __init__
    self._h5file = self._h5py.File(
  File "C:\Users\plnu\Anaconda3\envs\test_yadg5\lib\site-packages\h5py\_hl\files.py", line 562, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
  File "C:\Users\plnu\Anaconda3\envs\test_yadg5\lib\site-packages\h5py\_hl\files.py", line 235, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5f.pyx", line 102, in h5py.h5f.open
OSError: Unable to synchronously open file (file signature not found)`

**Comment by PeterKraus** [comment]
@NukP, the attached file is a `json` file renamed to `.nc`, generated with yadg version `0.post0.dev324`, which doesn't look right at all. Whatever you're doing, please try it with a clean installation of `yadg-5.0`, ideally in a new conda/venv environment...

Note that you can process these "older" json files, such as this one,  using `dgpost-2.1` by changing the load section to:

```
load:
  - as: dg
    path: $patch.json
    type: datagram
```

**Comment by PeterKraus** [comment]
@NukP please reopen this issue if it's not resolved.
