### ISSUE TITLE
Possible issue with Pint library version. 

### ISSUE THREAD

**Issue by NukP** [dgbowl/dgpost#92]
When running the following command:
 `dgpost ./Recipe/dgpost/dgpost.recipe.01_electro.yaml --patch ./Output/20230602-15p-Cu-PsA1-I-01/datagram_20230602-15p-Cu-PsA1-I-01 -v`

I received the following error 

```
Traceback (most recent call last):
  File "C:\Users\plnu\AppData\Local\miniconda3\envs\test_yadg\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\plnu\AppData\Local\miniconda3\envs\test_yadg\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\plnu\AppData\Local\miniconda3\envs\test_yadg\Scripts\dgpost.exe\__main__.py", line 4, in <module>
  File "C:\Users\plnu\AppData\Local\miniconda3\envs\test_yadg\lib\site-packages\dgpost\__init__.py", line 5, in <module>
    from .main import run_with_arguments, run
  File "C:\Users\plnu\AppData\Local\miniconda3\envs\test_yadg\lib\site-packages\dgpost\main.py", line 16, in <module>
    from dgpost.utils import parse, load, extract, transform, save, plot, pivot
  File "C:\Users\plnu\AppData\Local\miniconda3\envs\test_yadg\lib\site-packages\dgpost\utils\__init__.py", line 1, in <module>
    from .extract import extract
  File "C:\Users\plnu\AppData\Local\miniconda3\envs\test_yadg\lib\site-packages\dgpost\utils\extract.py", line 74, in <module>
    from dgpost.utils.helpers import (
  File "C:\Users\plnu\AppData\Local\miniconda3\envs\test_yadg\lib\site-packages\dgpost\utils\helpers.py", line 27, in <module>
    ureg.define("refractive_index_units = [] = RIU")
  File "C:\Users\plnu\AppData\Local\miniconda3\envs\test_yadg\lib\site-packages\pint\facets\plain\registry.py", line 469, in define
    self._helper_dispatch_adder(definition)
  File "C:\Users\plnu\AppData\Local\miniconda3\envs\test_yadg\lib\site-packages\pint\facets\plain\registry.py", line 492, in _helper_dispatch_adder
    adder_func(definition)
  File "C:\Users\plnu\AppData\Local\miniconda3\envs\test_yadg\lib\site-packages\pint\facets\group\registry.py", line 85, in _add_unit
    super()._add_unit(definition)
  File "C:\Users\plnu\AppData\Local\miniconda3\envs\test_yadg\lib\site-packages\pint\facets\nonmultiplicative\registry.py", line 72, in _add_unit
    super()._add_unit(definition)
  File "C:\Users\plnu\AppData\Local\miniconda3\envs\test_yadg\lib\site-packages\pint\facets\plain\registry.py", line 571, in _add_unit
    self._helper_adder(definition, self._units, self._units_casei)
  File "C:\Users\plnu\AppData\Local\miniconda3\envs\test_yadg\lib\site-packages\pint\facets\plain\registry.py", line 509, in _helper_adder
    self._helper_single_adder(
  File "C:\Users\plnu\AppData\Local\miniconda3\envs\test_yadg\lib\site-packages\pint\facets\plain\registry.py", line 532, in _helper_single_adder
    raise RedefinitionError(key, type(value))
pint.errors.RedefinitionError: Cannot redefine 'RIU' (<class 'pint.delegates.txt_defparser.plain.UnitDefinition'>)
``` 
 You can find the .nc file I used and the recipe [here](https://github.com/user-attachments/files/16598603/Github_issue_file.zip). This file was created using yadg5.1. When using yadg5.04 to process this experiment, the script ran just fine. 

I dug a bit deeper into the source of the error. The last pasrt where the traceback stay in dgpost is at line 27 in `dgpost\utils\helpers.py'  

Here the line that potentiall causing issue is 

```
ureg = pint.get_application_registry()

ureg.define("refractive_index_units = [] = RIU")
``` 
I isolated this code snippet into a separate jupyter notebook file (putting correct import for Pint of couse). I found that if I run this using Pint==0.23, then this snippet ran just fine. But if I use Pint==0.24.1 (which is required by yadg5.1) then I recevie the same error as I got above. Please let me know if you need any additional information on this. Thank you.

In addition, in order to test yadg5.1, I created a new conda environment for this. I found that if I just pip install yadg and dgpost directly, this will not work as the latest version of numpy 2 and pandas 2 has many incompatibility with many underlying library. With some experiment, I found that pandas==2.0.0 and numpy==1.23.5 works for the time being. You may would like to consider updating the requirement for yadg and dgpost with this.

**Comment by PeterKraus** [comment]
Yes, `RIU` have been added into pint recently (by me), so that definition has to be removed from `dgpost` to avoid conflicts.

I'm pretty sure `yadg` is compatible with the new numpy as well as with the old one. I think the `dgpost` compatibility will have to be checked. I don't recall requiring a particular version, but it might be related to the pint issue (as the last version without `RIU` doesn't support `numpy>=2`).

Feel free to submit a PR, I won't have time to touch this for the next month or so.
